package org.bea.backend.FakeTestData;

import org.bea.backend.model.IngredientCreate;
import org.bea.backend.model.Nutrient;
import org.bea.backend.model.Nutrients;

import static org.bea.backend.enums.NutrientType.MACRONUTRIENT;

public class IngredientCreateFakeData {
    public final static IngredientCreate ingredientCreate = new IngredientCreate(
            "Rindfleisch",
            "Rinderhack 20% Fett",
            100.0,
            "g",
            7.99
    );
    public final static Nutrients nutrients = new Nutrients(
            "nutrientId",
            new Nutrient("Energie",MACRONUTRIENT,250.0,"kcal"),
            new Nutrient("Energie",MACRONUTRIENT,250.0,"kJ"),
            new Nutrient("Fett",MACRONUTRIENT,250.0,"g"),
            new Nutrient("Eiweiß",MACRONUTRIENT,250.0,"g"),
            new Nutrient("Kohlenhydrate",MACRONUTRIENT,250.0,"g"),
            new Nutrient("Ballaststoffe",MACRONUTRIENT,250.0,"g"),
            new Nutrient("Wasser",MACRONUTRIENT,250.0,"g"),
            new Nutrient("Vitamin A",MACRONUTRIENT,250.0,"µg"),
            new Nutrient("Vitamin B1",MACRONUTRIENT,250.0,"µg"),
            new Nutrient("Vitamin B2",MACRONUTRIENT,250.0,"µg"),
            new Nutrient("Vitamin B3",MACRONUTRIENT,250.0,"µg"),
            new Nutrient("Vitamin B5",MACRONUTRIENT,250.0,"µg"),
            new Nutrient("Vitamin B6",MACRONUTRIENT,250.0,"µg"),
            new Nutrient("Vitamin B7",MACRONUTRIENT,250.0,"µg"),
            new Nutrient("Vitamin B9",MACRONUTRIENT,250.0,"µg"),
            new Nutrient("Vitamin B12",MACRONUTRIENT,250.0,"µg"),
            new Nutrient("Vitamin C",MACRONUTRIENT,250.0,"µg"),
            new Nutrient("Vitamin D",MACRONUTRIENT,250.0,"µg"),
            new Nutrient("Vitamin E",MACRONUTRIENT,250.0,"µg"),
            new Nutrient("Vitamin K",MACRONUTRIENT,250.0,"µg"),
            new Nutrient("Salz",MACRONUTRIENT,250.0,"g"),
            new Nutrient("PRAL",MACRONUTRIENT,250.0,"mg"),
            new Nutrient("Natrium",MACRONUTRIENT,250.0,"g"),
            new Nutrient("Kalium",MACRONUTRIENT,250.0,"g"),
            new Nutrient("Kalzium",MACRONUTRIENT,250.0,"mg"),
            new Nutrient("Magnesium",MACRONUTRIENT,250.0,"mg"),
            new Nutrient("Phosphor",MACRONUTRIENT,250.0,"mg"),
            new Nutrient("Schwefel",MACRONUTRIENT,250.0,"g"),
            new Nutrient("Chlorid",MACRONUTRIENT,250.0,"g"),
            new Nutrient("Eisen",MACRONUTRIENT,250.0,"mg"),
            new Nutrient("Zink",MACRONUTRIENT,250.0,"mg"),
            new Nutrient("Kupfer",MACRONUTRIENT,250.0,"mg"),
            new Nutrient("Mangan",MACRONUTRIENT,250.0,"mg"),
            new Nutrient("Fluorid",MACRONUTRIENT,250.0,"mg"),
            new Nutrient("Jod",MACRONUTRIENT,250.0,"µg"),
            new Nutrient("Isoleucin",MACRONUTRIENT,250.0,"g"),
            new Nutrient("Leucin",MACRONUTRIENT,250.0,"g"),
            new Nutrient("Lysin",MACRONUTRIENT,250.0,"mg"),
            new Nutrient("Methionin",MACRONUTRIENT,250.0,"mg"),
            new Nutrient("Cystein",MACRONUTRIENT,250.0,"mg"),
            new Nutrient("Phenylalanin",MACRONUTRIENT,250.0,"mg"),
            new Nutrient("Tyrosin",MACRONUTRIENT,250.0,"mg"),
            new Nutrient("Threonin",MACRONUTRIENT,250.0,"mg"),
            new Nutrient("Tryptophan",MACRONUTRIENT,250.0,"mg"),
            new Nutrient("Valin",MACRONUTRIENT,250.0,"mg"),
            new Nutrient("Arginin",MACRONUTRIENT,250.0,"mg"),
            new Nutrient("Histidin",MACRONUTRIENT,250.0,"mg"),
            new Nutrient("Alanin",MACRONUTRIENT,250.0,"mg"),
            new Nutrient("Asparaginsäure",MACRONUTRIENT,250.0,"mg"),
            new Nutrient("Glutaminsäure",MACRONUTRIENT,250.0,"mg"),
            new Nutrient("Glycin",MACRONUTRIENT,250.0,"mg"),
            new Nutrient("Prolin",MACRONUTRIENT,250.0,"mg"),
            new Nutrient("Serin",MACRONUTRIENT,250.0,"mg")
    );
    public final static Nutrient[] nutrientsArray = {
            nutrients.energyKcal(),
            nutrients.energyKJ(),
            nutrients.fat(),
            nutrients.protein(),
            nutrients.carbohydrate(),
            nutrients.fiber(),
            nutrients.water(),
            nutrients.vitaminA(),
            nutrients.vitaminB1(),
            nutrients.vitaminB2(),
            nutrients.vitaminB3(),
            nutrients.vitaminB5(),
            nutrients.vitaminB6(),
            nutrients.vitaminB7(),
            nutrients.vitaminB9(),
            nutrients.vitaminB12(),
            nutrients.vitaminC(),
            nutrients.vitaminD(),
            nutrients.vitaminE(),
            nutrients.vitaminK(),
            nutrients.salt(),
            nutrients.pral(),
            nutrients.sodium(),
            nutrients.potassium(),
            nutrients.calcium(),
            nutrients.magnesium(),
            nutrients.phosphorus(),
            nutrients.sulfur(),
            nutrients.chloride(),
            nutrients.iron(),
            nutrients.zinc(),
            nutrients.copper(),
            nutrients.manganese(),
            nutrients.fluoride(),
            nutrients.ioide(),
            nutrients.isoleucin(),
            nutrients.leucin(),
            nutrients.lysin(),
            nutrients.methionin(),
            nutrients.cystein(),
            nutrients.phenylalanin(),
            nutrients.tyrosin(),
            nutrients.threonin(),
            nutrients.tryptophan(),
            nutrients.valin(),
            nutrients.arginin(),
            nutrients.histidin(),
            nutrients.alanin(),
            nutrients.asparaginacid(),
            nutrients.glutaminacid(),
            nutrients.glycin(),
            nutrients.prolin(),
            nutrients.serin()
    };
}
