repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        files: ^ml-service/
      - id: end-of-file-fixer
        files: ^ml-service/
      - id: check-yaml
        files: ^ml-service/
      - id: check-added-large-files
        files: ^ml-service/

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.9
    hooks:
      # Run the linter.
      - id: ruff
        files: ^ml-service/
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
        files: ^ml-service/
